### ISSUE TITLE
Problem: environment variables not passed to NextCloud

### ISSUE THREAD

**Issue by lower29** [JiscRDSS/rdss-arkivum-nextcloud#9]
In PR #6 we made a change to allow the `DB_HOST` and `DB_NAME` parameters to be passed into the container via environment variables. However, it seems that the PHP-FPM executor sets [clear_env](http://php.net/manual/en/install.fpm.configuration.php) to `yes` by default, so these parameter values are not being made visible to the NextCloud PHP code.

This results in the following stack trace observed:

```
14:57:56  2018/01/12 14:57:56 [error] 183#183: *266 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve in /nextcloud/lib/private/DB/Connection.php:61
14:57:56  Stack trace:
14:57:56  #0 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
14:57:56  #1 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
14:57:56  #2 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
14:57:56  #3 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
14:57:56  #4 /nextcloud/lib/private/DB/Connection.php(148): Doctrine\DBAL\Connection->setTransactionIsolation(2)
14:57:56  #5 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\...
14:57:56  PHP message: PHP Fatal error: Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve in /nextcloud/lib/private/DB/Connection.php:61
14:57:56  Stack trace:
14:57:56  #0 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
14:57:56  #1 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
14:57:56  #2 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
14:57:56  #3 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
14:57:56  #4 /nextcloud/lib/private/DB/Connection.php(148): Doctrine\DBAL\Connection->setTransactionIsolation(2)
14:57:56  #5 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): O
14:57:56  10.0.3.78 - - [12/Jan/2018:14:57:56 +0000] "HEAD / HTTP/1.1" 500 0 "-" "-"
```

The hostname being passed in the environment variable `DB_HOST` is resolvable using `nslookup`, but not according to the PHP stack trace above, the key part being:

```
An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve in /nextcloud/lib/private/DB/Connection.php:61
```

This issue was first raised as [RDSSARK-414](https://jiscdev.atlassian.net/browse/RDSSARK-414).

**Comment by lower29** [comment]
I've been able to reproduce the problem in isolation using the following PHP script:
```
<?php

use Doctrine\Common\Classloader;
use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\DriverManager;

require '/nextcloud/3rdparty/doctrine/common/lib/Doctrine/Common/ClassLoader.php';

$cl_Common = new ClassLoader('Doctrine\Common', '/nextcloud/3rdparty/doctrine/common/lib/');
$cl_Common->register();
$cl_DBAL = new ClassLoader('Doctrine\DBAL', '/nextcloud/3rdparty/doctrine/dbal/lib/');
$cl_DBAL->register();

$config = new \Doctrine\DBAL\Configuration();

// Uncomment to use DB_HOST env var for dbhost param
$dbhost = getenv('DB_HOST');
// Uncomment to use hardcoded value for dbhost param
//$dbhost = 'mysql';

$params = array(
    'driver' => 'pdo_mysql',
    'charset' => 'UTF8',
    'host' => $dbhost,
    'dbname' => getenv('DB_NAME'),
    'user' => getenv('DB_USER'),
    'password' => getenv('DB_PASSWORD')
);

$eventManager = new \Doctrine\Common\EventManager();

$conn = DriverManager::getConnection($params, $config, $eventManager);
$conn->setTransactionIsolation(Connection::TRANSACTION_READ_COMMITTED);

?>
```
With the `$dbhost` set to `getenv('DB_HOST')`, there is no error. With `$dbhost` set to `'mysql'`, which would be the default in our NextCloud configuration if the `DB_HOST` environment variable is empty, the same error occurs that was reported; the name cannot be resolved.

This test was executed on the same NextCloud instance as the problem was reported on, although the same result has been produced on my local development environment too.

This suggests that, once the environment variable value is passed correctly to the NextCloud PHP code, the problem with the database server's address being unresolved will be fixed too, i.e. no other code change is required.
